# Generated by Django 4.2.7 on 2025-03-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherche',
            name='terme_recherche',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Terme de recherche'),
        ),
    ]
