# Generated by Django 4.2.7 on 2025-03-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0003_entreprise_document_type_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ressource',
        ),
    ]
