# Generated by Django 4.2.7 on 2025-03-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0005_remove_entreprise_rap_app_ent_est_act_c3aa9b_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['formation', '-created_at'], 'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='auteur',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='saturation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Niveau de saturation (%)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='dernier_commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Dernier commentaire'),
        ),
        migrations.AddField(
            model_name='formation',
            name='saturation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Niveau de saturation (%)'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='rap_app.utilisateur', verbose_name='Utilisateur associé'),
        ),
        migrations.AddIndex(
            model_name='commentaire',
            index=models.Index(fields=['formation'], name='rap_app_com_formati_0c3422_idx'),
        ),
    ]
