# Generated by Django 4.2.7 on 2025-03-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0006_alter_commentaire_options_remove_commentaire_auteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='taille_fichier',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (Ko)'),
        ),
    ]
