# Generated by Django 4.2.7 on 2025-03-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0007_document_taille_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='saturation',
        ),
        migrations.AlterField(
            model_name='evenement',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date de l'événement"),
        ),
    ]
