# Generated by Django 4.2.7 on 2025-03-08 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rap_app', '0008_remove_formation_saturation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user_permissions',
        ),
        migrations.AlterModelOptions(
            name='historiqueformation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historique de formation', 'verbose_name_plural': 'Historiques des formations'},
        ),
        migrations.RemoveField(
            model_name='recherche',
            name='adresse_ip',
        ),
        migrations.RemoveField(
            model_name='recherche',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='recherche',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='formation',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='historiqueformation',
            name='saturation',
            field=models.FloatField(blank=True, null=True, verbose_name='Niveau de saturation (%)'),
        ),
        migrations.AddField(
            model_name='historiqueformation',
            name='taux_remplissage',
            field=models.FloatField(blank=True, null=True, verbose_name='Taux de remplissage (%)'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='annee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='inscrits_crif',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Inscrits CRIF'),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='inscrits_mp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Inscrits MP'),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='inscrits_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total inscrits'),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='mois',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='total_places',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total places'),
        ),
        migrations.AlterField(
            model_name='historiqueformation',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_utilisateurs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ayant modifié'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='statut',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='typeoffre',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AddIndex(
            model_name='historiqueformation',
            index=models.Index(fields=['formation'], name='rap_app_his_formati_aa2815_idx'),
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
