# Generated by Django 4.2.7 on 2025-03-08 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rap_app', '0009_remove_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='saturation',
            field=models.FloatField(blank=True, null=True, verbose_name='Taux de saturation (%)'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
