# Generated by Django 4.2.7 on 2025-03-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap_app', '0010_formation_saturation_alter_formation_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='saturation',
        ),
    ]
