# Generated by Django 4.2.7 on 2025-03-10 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rap_app', '0011_remove_formation_saturation'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description de la relation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='assistante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assistante'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='cap',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité maximale'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='entreprises',
            field=models.ManyToManyField(blank=True, related_name='formations', to='rap_app.entreprise', verbose_name='Partenaires'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='prevus_crif',
            field=models.PositiveIntegerField(default=0, verbose_name='Places prévues CRIF'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='prevus_mp',
            field=models.PositiveIntegerField(default=0, verbose_name='Places prévues MP'),
        ),
    ]
